taxes:
  2020:
  # https://www.rijksoverheid.nl/onderwerpen/huis-kopen/vraag-en-antwoord/recht-op-hypotheekrenteaftrek
    mortgage_interest_deduction: 0.46
    cost_of_home_ownership: 0.006 # eigen woning forfait (voor WOZ <= 1.080.000E)
    income_tax:
      brackets: [ 0, 68508 ]
      rates: [ 0.3735, 0.4950 ]
    wealth_tax:
      brackets: [ 0, 72798, 1005573 ]
      rates: [0.01789, 0.04185, 0.0528]
    work_discount:
      # https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/heffingskortingen/arbeidskorting/tabel-arbeidskorting-2020
      brackets: [0, 9921, 21430, 34954, 98604]
      rates: [0.02812, 0.28812, 0.01656, -0.06, 0.0]
      base_amounts: [0, 279, 3595, 3819, 0]
    regular_tax_discount:
      brackets: [0, 20711, 68507]
      base_amount: [2711, 2711, 0]
      rates: [0, -0.05672, 0]
    capital_gains_tax:
  #    https://www:belastingdienst:nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/vermogen_en_aanmerkelijk_belang/vermogen/belasting_betalen_over_uw_vermogen/grondslag_sparen_en_beleggen/berekening-2020
      savings_rate: 0.0007
      investment_rate: 0.0528
      tax_rate: 0.30
      savings_weights: [0.67, 0.21, 0.0]
      brackets: [0, 72798, 1005573]
  2021:
    mortgage_interest_deduction: 0.43
    cost_of_home_ownership: 0.005% # (voor WOZ <= 1.100.000E)
    income_tax:
      # https://www.belastingdienst.nl/wps/wcm/connect/nl/werk-en-inkomen/content/hoeveel-inkomstenbelasting-betalen
      brackets: [ 0, 68508 ]
      rates: [ 0.3710, 0.4950 ]
    wealth_tax:
      # https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/vermogen_en_aanmerkelijk_belang/vermogen/belasting_betalen_over_uw_vermogen/grondslag_sparen_en_beleggen/berekening-2021/berekening-belasting-over-inkomen-uit-vermogen-over-2021
      brackets: [ 0, 50000, 950000 ]
      rates: [ 0.01898, 0.04501, 0.0569 ]
    work_discount:
      # https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/heffingskortingen/arbeidskorting/tabel-arbeidskorting-2021
      brackets: [ 0, 10108, 21835, 35652, 105736 ]
      rates: [ 0.02371, 0.14890, 0.01378, -0.03105, 0.0 ]
      base_amounts: [ 0, 240, 1987, 2178, 0 ]
    regular_tax_discount:
      # https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/inkomstenbelasting/heffingskortingen_boxen_tarieven/heffingskortingen/algemene_heffingskorting/tabel-algemene-heffingskorting-2021
      brackets: [ 0, 21043, 68507 ]
      base_amount: [ 1469, 1469, 0 ]
      rates: [ 0, -0.03093, 0 ]
    capital_gains_tax:
      #    https://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/prive/vermogen_en_aanmerkelijk_belang/vermogen/belasting_betalen_over_uw_vermogen/grondslag_sparen_en_beleggen/berekening-2021/:
      savings_rate: 0.0003
      investment_rate: 0.0569
      tax_rate: 0.31
      savings_weights: [ 0.67, 0.21, 0.0 ]
      brackets: [ 0, 50000, 950000 ]
    2022:
      mortgage_interest_deduction: 0.40
    2023:
      mortgage_interest_deduction: 0.3705
economy:
  inflation: 3.15
mortgage:
  duration: 30 # years
  size: 300000
  interest_rate: 1.7%
  interest_discount: 15%
  interest_discount_bounds: [0.5, 1]
#  type: 'linear'
  type: 'annuity'
salary:
  amount: 55000 # Euro / year
  holiday_allowance: 0.08
simulation:
  step_size: 'month'
  length: 30 # years
assets:
  stocks:
    returns: 0.07 # return / year
    start_value: 10000 # Euro
